services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pets
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"    # API Port
      - "9001:9001"    # Console Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    restart: always
