"""added image field to pet model

Revision ID: 0fb993a68278
Revises: 52e30758c028
Create Date: 2026-04-05 01:03:20.452607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fb993a68278"
down_revision: Union[str, Sequence[str], None] = "52e30758c028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pets", sa.Column("image", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pets", "image")
    # ### end Alembic commands ###
